/**
 * Optional export of the practice detectors as command hooks for BOTH hook
 * bridges the harness ships (`dsh-hooks-claude-code`, `dsh-hooks-codex`).
 *
 * The native waterfall (`tools/pre-execute`) is the primary mechanism and the
 * plugin is complete without either bridge. This exists for users who already
 * run hooks in one of those dialects, or who want the same gates in a
 * project's own hook file. One declaration → two files; each hook runs
 * `dsh-skill-presets check <practice> --cwd <dir>`, which exits 2 (block, with
 * the reason on stderr) only when the practice is RED and configured `hard`.
 * @module dsh-skill-presets/host/hooks
 */

import type { PracticeId } from './types.ts'

/** Which harness event each practice gates, and which tools it watches. */
export const HOOK_PLAN: readonly { practice: PracticeId, event: 'PreToolUse' | 'Stop', tools: readonly string[] }[] = [
  { practice: 'worktree', event: 'PreToolUse', tools: ['write', 'edit', 'bash'] },
  { practice: 'conductor', event: 'PreToolUse', tools: ['write', 'edit', 'bash'] },
  { practice: 'plan-before-code', event: 'PreToolUse', tools: ['write', 'edit'] },
  { practice: 'plan-drift', event: 'PreToolUse', tools: ['write', 'edit'] },
  { practice: 'pull-request', event: 'Stop', tools: [] },
]

export interface HookFile {
  hooks: Record<string, { matcher?: string, hooks: { type: 'command', command: string, timeout?: number }[] }[]>
}

/**
 * Build the hook config for one dialect.
 * @param dialect - matcher grammar differs: Claude Code accepts `a|b` literal
 *   alternatives (also a regex); Codex is always an unanchored regex.
 * @param bin - the command that runs the checker; defaults to the published bin name.
 */
export function buildHookFile(dialect: 'claude-code' | 'codex', bin = 'dsh-skill-presets'): HookFile {
  const hooks: HookFile['hooks'] = {}
  for (const entry of HOOK_PLAN) {
    const command = `${bin} check ${entry.practice} --hook ${dialect}`
    const group = {
      ...(entry.event === 'PreToolUse'
        ? { matcher: dialect === 'codex' ? `^(?:${entry.tools.join('|')})$` : entry.tools.join('|') }
        : {}),
      hooks: [{ type: 'command' as const, command, timeout: 20 }],
    }
    hooks[entry.event] = [...(hooks[entry.event] ?? []), group]
  }
  return { hooks }
}

/** Render a hook file with a leading comment-free header field, since JSON has no comments. */
export function renderHookFile(dialect: 'claude-code' | 'codex', bin?: string): string {
  const file = buildHookFile(dialect, bin)
  return `${JSON.stringify({
    $comment: `Generated by dsh-skill-presets for ${dialect === 'codex' ? 'dsh-hooks-codex' : 'dsh-hooks-claude-code'}. `
      + 'Each hook replays a practice detector against live git facts; it blocks (exit 2) only when the practice is red AND set to hard in practices.json. '
      + 'The native tools/pre-execute gate is the primary mechanism; this file is a convenience for hook-based setups.',
    ...file,
  }, null, 2)}\n`
}

/**
 * Parse the hook payload a bridge writes to stdin. Both dialects carry the
 * tool name and, for shell tools, the command; Claude Code nests the full
 * tool input, Codex exposes `tool_input.command` only.
 */
export function parseHookStdin(text: string): { toolName?: string, filePath?: string, command?: string, cwd?: string, sessionId?: string } {
  try {
    const raw = JSON.parse(text) as Record<string, unknown>
    const input = (typeof raw.tool_input === 'object' && raw.tool_input !== null ? raw.tool_input : {}) as Record<string, unknown>
    return {
      ...(typeof raw.tool_name === 'string' ? { toolName: raw.tool_name } : {}),
      ...(typeof input.file_path === 'string' ? { filePath: input.file_path } : typeof input.path === 'string' ? { filePath: input.path } : {}),
      ...(typeof input.command === 'string' ? { command: input.command } : {}),
      ...(typeof raw.cwd === 'string' ? { cwd: raw.cwd } : {}),
      ...(typeof raw.session_id === 'string' ? { sessionId: raw.session_id } : {}),
    }
  } catch {
    return {}
  }
}
